Solution to Lab 1

This section identifies imported packages

In [1]:
import numpy as np
import random as rd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Part A
Question 1

In [4]:
array_dm_1 = np.arange(1,21,3)
array_dm_1

array([ 1,  4,  7, 10, 13, 16, 19])

Question 2

In [5]:
np.random.seed(101)
array_dm_2 = np.random.rand(3)
array_dm_2

array([0.51639863, 0.57066759, 0.02847423])

Question 3

In [9]:
tdarray_dm = np.array([[10,20,45],[30,12,16],[42,17,56]])
tdarray_dm

tdarray_dm[:2,:]
tdarray_dm[1:,:]

array([[10, 20, 45],
       [30, 12, 16],
       [42, 17, 56]])

array([[10, 20, 45],
       [30, 12, 16]])

array([[30, 12, 16],
       [42, 17, 56]])

Question 4

In [12]:
A_dm = np.array([[1,2],[3,4]])
B_dm = np.array([[5,6],[7,8]])

A_dm
B_dm
vab_dn = np.vstack((A_dm,B_dm))
vab_dn

hab_dn= np.hstack((A_dm,B_dm))
hab_dn

np.vsplit(hab_dn,2)

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]

Question 5

In [17]:
X_dm = np.array([[5,7,2],[4,5,6],[7,4,2]])
Y_dm = np.array([[4,2],[6,2],[4,2]])
X_dm
Y_dm
np.dot(X_dm,Y_dm)
#np.dot(Y_dm,X_dm)



array([[5, 7, 2],
       [4, 5, 6],
       [7, 4, 2]])

array([[4, 2],
       [6, 2],
       [4, 2]])

array([[70, 28],
       [70, 30],
       [60, 26]])

Question 6

In [21]:
X_dm = np.array([2,-1,-8])
Y_dm = np.array([3,2,-1])

X_dm
Y_dm

X_dm.shape
X_dm.size
X_dm.ndim

Xn_dm = X_dm.reshape(3,1)
Yn_dm = Y_dm.reshape(3,1)

Xn_dm
Xn_dm.shape
Xn_dm.size
Xn_dm.ndim

array([ 2, -1, -8])

array([ 3,  2, -1])

(3,)

3

1

array([[ 2],
       [-1],
       [-8]])

(3, 1)

3

2

Question 7

In [24]:
#Broadcasting Exllanation

D_dm = np.array([[1,2,3],[4,5,6],[7,8,9]])
D_dm

E_dm = np.array([[-3,-2,-1]])
E_dm

D_dm - E_dm

#F_dm = np.array([[2,3,4],[5,6,7][8,9,10]])

#D_dm - F_dm

#D_dm*E_dm


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[-3, -2, -1]])

array([[ 4,  4,  4],
       [ 7,  7,  7],
       [10, 10, 10]])

Part B

Question 1

In [ ]:

A_dm = np.array([[4, 1, -2],[2, -3, 2],[1, 2, 3]])
A_dm
np.linalg.det(A_dm)
B_dm = np.array([10,-4,6])
B_dm

np.linalg.solve(A_dm,B_dm)


array([[ 4,  1, -2],
       [ 2, -3,  2],
       [ 1,  2,  3]])

np.float64(-70.00000000000003)

array([10, -4,  6])

array([ 1.8,  2.4, -0.2])

Question 2

In [30]:
A2_dm = np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]])
A2_dm
B2_dm = np.array([10,20,3,-1])
B2_dm

np.linalg.det(A2_dm)
#np.linalg.solve(A2_dm,B2_dm)


array([[ 2, -1,  3,  4],
       [ 4, -2,  6,  8],
       [ 3,  1, -2,  2],
       [ 1,  3, -4,  1]])

array([10, 20,  3, -1])

np.float64(0.0)