Solution to Lab 1

This section identifies imported packages

In [31]:
import numpy as np
import random as rd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Part A
Question 1

In [ ]:
array_jg_1 = np.arange(1,21,3)
array_jg_1

array([ 1,  4,  7, 10, 13, 16, 19])

Question 2

In [ ]:
np.random.seed(101)
array_jg_2 = np.random.rand(3)
array_jg_2

array([0.51639863, 0.57066759, 0.02847423])

Question 3

In [ ]:
tdarray_jg = np.array([[10,20,45],[30,12,16],[42,17,56]])
tdarray_jg

tdarray_jg[:2,:]
tdarray_jg[1:,:]

array([[10, 20, 45],
       [30, 12, 16],
       [42, 17, 56]])

array([[10, 20, 45],
       [30, 12, 16]])

array([[30, 12, 16],
       [42, 17, 56]])

Question 4

In [ ]:
A_jg = np.array([[1,2],[3,4]])
B_jg = np.array([[5,6],[7,8]])

A_jg
B_jg
vab_jg = np.vstack((A_jg,B_jg))
vab_jg

hab_jg= np.hstack((A_jg,B_jg))
hab_jg

np.vsplit(hab_jg,2)

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]

Question 5

In [ ]:
X_jg = np.array([[5,7,2],[4,5,6],[7,4,2]])
Y_jg = np.array([[4,2],[6,2],[4,2]])
X_jg
Y_jg
np.dot(X_jg,Y_jg)



array([[5, 7, 2],
       [4, 5, 6],
       [7, 4, 2]])

array([[4, 2],
       [6, 2],
       [4, 2]])

array([[70, 28],
       [70, 30],
       [60, 26]])

Question 6

In [ ]:
X_jg = np.array([2,-1,-8])
Y_jg = np.array([3,2,-1])

X_jg
Y_jg

X_jg.shape
X_jg.size
X_jg.ndim

Xn_jg = X_jg.reshape(3,1)
Yn_jg = Y_jg.reshape(3,1)

Xn_jg
Xn_jg.shape
Xn_jg.size
Xn_jg.ndim

array([ 2, -1, -8])

array([ 3,  2, -1])

(3,)

3

1

array([[ 2],
       [-1],
       [-8]])

(3, 1)

3

2

Question 7

In [ ]:
#Broadcasting Exllanation

D_jg = np.array([[1,2,3],[4,5,6],[7,8,9]])
D_jg

E_jg = np.array([[-3,-2,-1]])
E_jg

D_jg - E_jg

#F_jg = np.array([[2,3,4],[5,6,7][8,9,10]])

#D_jg - F_jg

#D_jg*E_jg


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[-3, -2, -1]])

array([[ 4,  4,  4],
       [ 7,  7,  7],
       [10, 10, 10]])

Part B

Question 1

In [ ]:

A_jg = np.array([[4, 1, -2],[2, -3, 2],[1, 2, 3]])
A_jg
np.linalg.det(A_jg)
B_jg = np.array([10,-4,6])
B_jg

np.linalg.solve(A_jg,B_jg)


array([[ 4,  1, -2],
       [ 2, -3,  2],
       [ 1,  2,  3]])

np.float64(-70.00000000000003)

array([10, -4,  6])

array([ 1.8,  2.4, -0.2])

Question 2

In [ ]:
A2_jg = np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]])
A2_jg
B2_jg = np.array([10,20,3,-1])
B2_jg

np.linalg.det(A2_jg)
#np.linalg.solve(A2_jg,B2_jg)


array([[ 2, -1,  3,  4],
       [ 4, -2,  6,  8],
       [ 3,  1, -2,  2],
       [ 1,  3, -4,  1]])

array([10, 20,  3, -1])

np.float64(0.0)